name: Check JFrog CLI

on:
  workflow_dispatch:   # Run manually from the Actions tab
  push:                # Optional - run on push
    branches:
      - main

jobs:
  check-jfrog-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/jfrog
          jfrog --version

      - name: Verify JFrog CLI configuration
        run: |
          echo "JFrog CLI version:"
          jfrog --version
          echo "JFrog CLI help (subset):"
          jfrog -h | head -n 15
      - name: Check if JFrog CLI is installed
        run: |
          if command -v jfrog >/dev/null 2>&1; then
            echo "✅ JFrog CLI is installed."
            jfrog --version
          else
            echo "❌ JFrog CLI is NOT installed on this runner."
            exit 1
          fi

      - name: Check if JFrog CLI is configured
        run: |
          CONFIG_OUTPUT=$(jfrog config show 2>&1 || true)
          if echo "$CONFIG_OUTPUT" | grep -q "Server ID"; then
            echo "✅ JFrog CLI is configured:"
            echo "$CONFIG_OUTPUT"
          else
            echo "⚠️ JFrog CLI is NOT configured."
            echo "$CONFIG_OUTPUT"
          fi
     

